name: veronikadoljenkova
favicon: null
layout_spectrum: 0.92081
typography_spectrum: 0.36284
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00b7a5'
    - '#040300'
    - '#544948'
    - '#7a6e6c'
    - '#fefbfe'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
